name = "stats"
route = 'stats.discordtickets.app/*'
main = "./src/index.js"
account_id = "97b58167ff9c21fe35e878e6a65654f8"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-05-13"
# webpack_config = "webpack.config.js"
kv_namespaces = [ 
    { binding = "CACHE", id = "397e16415fda43058a7cc72b3413bfd1", preview_id="397e16415fda43058a7cc72b3413bfd1" }
]


[triggers]
  crons = ["0 0 * * *"]

[vars]
  REALM_APP_ID = "cloudflare-jhcqs"
  TOPGG_ID = "964624470985826374"

# [secrets]
# REALM_API_KEY
# TOPGG_TOKEN