name = "stats"
type = "webpack"
route = 'stats.discordtickets.app/*'
main = "./index.js"
account_id = "97b58167ff9c21fe35e878e6a65654f8"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-05-13"
# webpack_config = "webpack.config.js"

[triggers]
  crons = ["0 0 * * *"]


[vars]
  SUPABASE_URL =  "https://zbewungpmxujmlpnbfra.supabase.co"

# [secrets]
# SUPABASE_SECRET
